#!/bin/bash
# ===========================================
# Ayaan's Gmail Autoresponder Agent - Environment Setup
# ===========================================
# This script creates the .env file with your credentials
# Run: ./scripts/setup-env.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Ayaan's Gmail Autoresponder Agent - Environment Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Keeping existing .env file${NC}"
        exit 0
    fi
fi

echo ""
echo -e "${YELLOW}Ollama Cloud API Configuration${NC}"
echo -e "Get your API key from: ${BLUE}https://ollama.com/settings/keys${NC}"
echo ""

read -p "Enter Ollama API Key: " OLLAMA_API_KEY
read -p "Enter Ollama Base URL [https://api.ollama.com]: " OLLAMA_BASE_URL
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-https://api.ollama.com}
read -p "Enter Ollama Model [llama3.2]: " OLLAMA_MODEL
OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}

echo ""
echo -e "${YELLOW}Gmail OAuth2 Configuration${NC}"
echo -e "Get credentials from: ${BLUE}https://console.cloud.google.com/apis/credentials${NC}"
echo ""

read -p "Enter Gmail Client ID: " GMAIL_CLIENT_ID
read -p "Enter Gmail Client Secret: " GMAIL_CLIENT_SECRET

# Create .env file
cat > .env << EOF
# ===========================================
# Ayaan's Gmail Autoresponder Agent Configuration
# ===========================================
# Generated by setup-env.sh on $(date)

# ---- Ollama Cloud API ----
OLLAMA_API_KEY=${OLLAMA_API_KEY}
OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
OLLAMA_MODEL=${OLLAMA_MODEL}

# ---- Gmail OAuth2 ----
GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}

# ---- Optional ----
# TOKEN_FILE=token.json
# CREDENTIALS_FILE=credentials.json
EOF

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ .env file created successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run: make run     (start the server)"
echo "  2. Use /auth/url API to authenticate Gmail"
echo ""
